[theme]
base = "dark"
primaryColor = "#00fc3fff"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#141414"
#textColor = "#e6debe"
showSidebarBorder=true
font = "Inter:https://fonts.googleapis.com/css2?family=Inter&display=swap"
#baseFontWeight = 300
headingFontWeights = 400